%YAML 1.2
---
# Rationale: COPYING.txt contains the official plain text version of CC0 [1].
# From a copyright perspective, it’s OK to modify CC0’t text [2]. The caveat is
# that CC0 contains trademarks that are owned by Creative Commons [3]. Creative
# Commons does give us a license to use those trademarks, but that license
# stipulates that you can’t use those trademarks with modified versions of
# Creative Commons legal tools. CC0 is a Creative Commons legal tool [4], so if
# we modify CC0, then we have to remove any Creative Commons trademarks from it.
#
# Excluding COPYING.txt makes sure that pre-commit won’t inadvertently encourage
# someone to modify CC0’s text.
#
# yamllint disable rule:line-length
# [1]: <https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F>
# [2]: <https://github.com/creativecommons/creativecommons.org/issues/1218#issuecomment-1212525987>
# [3]: <https://creativecommons.org/policies/#trademark>
# [4]: <https://creativecommons.org/faq/#what-is-creative-commons-and-what-do-you-do>
# yamllint enable
exclude: "^COPYING\\.txt$"
repos:
    -
        repo: meta
        hooks:
            - id: check-useless-excludes
    -
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            - id: check-case-conflict
            - id: check-merge-conflict
            - id: check-symlinks
            - id: check-vcs-permalinks
            - id: destroyed-symlinks
            - id: end-of-file-fixer
            - id: fix-byte-order-marker
            - id: mixed-line-ending
            - id: trailing-whitespace
    -
        repo: https://github.com/igorshubovych/markdownlint-cli
        rev: v0.32.1
        hooks:
            - id: markdownlint
    -
        repo: https://github.com/adrienverge/yamllint
        rev: v1.27.1
        hooks:
            - id: yamllint
